name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file dockerfile --tag charlyreux/mywebsite:latest
    - name: Login to dockerhub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u charlyreux --password-stdin
    - name: Push the Docker image
      run: docker push charlyreux/mywebsite:latest
